///////////////////////////////////////////////////////////
//  EntranceType.cs
//  Implementation of the Enumeration EntranceType
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:49:01 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Common.Contracts
{

    public enum EntranceType : int
    {

        LEFT,
        RIGHT

    }//end EntranceType
}