///////////////////////////////////////////////////////////
//  ICountryService.cs
//  Implementation of the Interface ICountryService
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:49:01 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;
using Common.DomainModels;

namespace Common.Contracts
{
    [ServiceContract]
    public interface ICountryService
    {
        [OperationContract]
        /// 
        /// <param name="id"></param>
        Country GeCountryByID(int id);

        [OperationContract]
        /// 
        /// <param name="name"></param>
        Country GetCountryByName(string name);

        [OperationContract]
        List<Country> GetAll();
    }//end ICountryService
}