///////////////////////////////////////////////////////////
//  ILogging.cs
//  Implementation of the Interface ILogging
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:49:01 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Common.Contracts
{

    public interface ILogging
    {

        /// 
        /// <param name="message"></param>
        /// <param name="logType"></param>
        void LogNewMessage(string message, LogType logType);
    }//end ILogging
}