///////////////////////////////////////////////////////////
//  IPlaceService.cs
//  Implementation of the Interface IPlaceService
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:49:01 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;
using Common.DomainModels;

namespace Common.Contracts
{
    [ServiceContract]
    public interface IPlaceService
    {

        [OperationContract]
        /// 
        /// <param name="place"></param>
        bool AddPlace(Place place);

        [OperationContract]
        /// 
        /// <param name="place"></param>
        bool DeletePlace(int placeID);

        [OperationContract]
        List<Place> GetAllPlaces();

        [OperationContract]
        /// 
        /// <param name="id"></param>
        Place GetPlaceByID(int id);

        [OperationContract]
        /// 
        /// <param name="newData"></param>
        bool UpdatePlace(Place newData);
    }//end IPlaceService
}