///////////////////////////////////////////////////////////
//  IStationService.cs
//  Implementation of the Interface IStationService
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:49:01 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;
using Common.DomainModels;

namespace Common.Contracts
{

    [ServiceContract]
    public interface IStationService
    {

        [OperationContract]
        /// 
        /// <param name="station"></param>
        bool AddStation(Station station);

        [OperationContract]
        /// 
        /// <param name="newData"></param>
        bool ChangeStation(Station newData);

        [OperationContract]
        /// 
        /// <param name="station"></param>
        bool DeleteStation(int stationID);

        [OperationContract]
        List<Station> GetAllStations();

        [OperationContract]
        /// 
        /// <param name="id"></param>
        Station GetStationByID(int id);
    }//end IStationService
}