///////////////////////////////////////////////////////////
//  ITrackService.cs
//  Implementation of the Interface ITrackService
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:49:01 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.ServiceModel;
using Common.DomainModels;

namespace Common.Contracts
{

    [ServiceContract]
    public interface ITrackService
    {

        [OperationContract]
        /// 
        /// <param name="track"></param>
        bool AddTrack(Track track);

        [OperationContract]
        /// 
        /// <param name="track"></param>
        bool DeleteTrack(int trackID);

        [OperationContract]
        List<Track> GetAllTracks();

        [OperationContract]
        List<Track> GetUnattachedTracks();

        [OperationContract]
        /// 
        /// <param name="id"></param>
        Track GetTrackByID(int id);

        [OperationContract]
        /// 
        /// <param name="newData"></param>
        bool UpdateTrack(Track newData);
    }//end ITrackService
}