///////////////////////////////////////////////////////////
//  Validation.cs
//  Implementation of the Class Validation
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:50:03 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Runtime.Serialization;

namespace Common.Contracts
{

    public interface IInternalValidation
    {


        bool IsValid();

    }//end Validation
}