///////////////////////////////////////////////////////////
//  LogType.cs
//  Implementation of the Enumeration LogType
//  Generated by Enterprise Architect
//  Created on:      30-Jul-2020 3:49:02 PM
//  Original author: Predrag
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;

namespace Common.Contracts
{

    public enum LogType : int
    {

        INFO,
        WARNING,
        DEBUG,
        ERROR

    }//end LogType
}